import { ThemeIconMap } from '../../types';
import {
  TrophyIcon,
  GamepadIcon,
  JoystickIcon,
  StarIcon,
  SkullIcon,
  PortalIcon,
  IceIcon,
  LightningIcon,
  SwitchIcon,
  BoxIcon,
  TargetIcon,
  ClockIcon,
  HourglassIcon,
  FootstepsIcon,
  FlagIcon,
  PartyIcon,
  ExplosionIcon,
  PlugIcon,
  KeyIcon,
  MountainIcon,
  MedalIcon,
  ArchitectIcon,
  CrownIcon,
  RetroBlockIcon,
  GalaxyIcon,
  RulerIcon,
} from './gameplayIcons';

import {
  MenuIcon,
  CloseIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  SearchIcon,
  PinIcon,
  MapIcon,
  FullscreenIcon,
  MinimizeIcon,
  RefreshIcon,
  RepeatIcon,
  BackspaceIcon,
  ExternalLinkIcon,
} from './navigationIcons';

import {
  PencilIcon,
  PaletteIcon,
  SaveIcon,
  PlusIcon,
  TrashIcon,
  CopyIcon,
  ClipboardIcon,
  EraseIcon,
  ImportIcon,
  FolderIcon,
  WoodIcon,
  GridIcon,
  SparklesIcon,
  DotIcon,
  RobotIcon,
  BookIcon,
  TemplateIcon,
  ToolsIcon,
} from './editorIcons';

import {
  UserIcon,
  FriendsIcon,
  ChatIcon,
  MailIcon,
  HeartIcon,
  ShieldIcon,
  AwardIcon,
  CoffeeIcon,
  ThumbsUpIcon,
  ThumbsDownIcon,
  CreditCardIcon,
  TagIcon,
  GlobeIcon,
  CoinsIcon,
} from './socialIcons';

import {
  WarningIcon,
  CheckIcon,
  ErrorIcon,
  SettingsIcon,
  LockIcon,
  UnlockIcon,
  VolumeOnIcon,
  VolumeOffIcon,
  EyeIcon,
  EyeOffIcon,
  BarChartIcon,
  TrendUpIcon,
  LightbulbIcon,
  BanIcon,
  LoaderIcon,
  KeyboardIcon,
} from './systemIcons';

export const classicIcons: ThemeIconMap = {
  // Gameplay
  'trophy': TrophyIcon,
  'gamepad': GamepadIcon,
  'joystick': JoystickIcon,
  'star': StarIcon,
  'skull': SkullIcon,
  'portal': PortalIcon,
  'ice': IceIcon,
  'lightning': LightningIcon,
  'switch': SwitchIcon,
  'box': BoxIcon,
  'target': TargetIcon,
  'clock': ClockIcon,
  'timer': ClockIcon,
  'hourglass': HourglassIcon,
  'footsteps': FootstepsIcon,
  'flag': FlagIcon,
  'party': PartyIcon,
  'explosion': ExplosionIcon,
  'plug': PlugIcon,
  'key': KeyIcon,
  'mountain': MountainIcon,
  'medal': MedalIcon,
  'architect': ArchitectIcon,
  'crown': CrownIcon,
  'retro-block': RetroBlockIcon,
  'galaxy': GalaxyIcon,
  'ruler': RulerIcon,

  // Navigation
  'menu': MenuIcon,
  'close': CloseIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-up': ArrowUpIcon,
  'arrow-down': ArrowDownIcon,
  'search': SearchIcon,
  'pin': PinIcon,
  'map': MapIcon,
  'fullscreen': FullscreenIcon,
  'minimize': MinimizeIcon,
  'refresh': RefreshIcon,
  'repeat': RepeatIcon,
  'backspace': BackspaceIcon,
  'external-link': ExternalLinkIcon,

  // Editor & Tools
  'pencil': PencilIcon,
  'palette': PaletteIcon,
  'save': SaveIcon,
  'plus': PlusIcon,
  'trash': TrashIcon,
  'copy': CopyIcon,
  'clipboard': ClipboardIcon,
  'erase': EraseIcon,
  'import': ImportIcon,
  'folder': FolderIcon,
  'wood': WoodIcon,
  'grid': GridIcon,
  'sparkles': SparklesIcon,
  'dot': DotIcon,
  'robot': RobotIcon,
  'book': BookIcon,
  'template': TemplateIcon,
  'tools': ToolsIcon,

  // Social & Monetization
  'user': UserIcon,
  'friends': FriendsIcon,
  'chat': ChatIcon,
  'mail': MailIcon,
  'heart': HeartIcon,
  'shield': ShieldIcon,
  'award': AwardIcon,
  'coffee': CoffeeIcon,
  'thumbs-up': ThumbsUpIcon,
  'thumbs-down': ThumbsDownIcon,
  'credit-card': CreditCardIcon,
  'tag': TagIcon,
  'globe': GlobeIcon,
  'coins': CoinsIcon,

  // System
  'warning': WarningIcon,
  'check': CheckIcon,
  'error': ErrorIcon,
  'settings': SettingsIcon,
  'lock': LockIcon,
  'unlock': UnlockIcon,
  'volume-on': VolumeOnIcon,
  'volume-off': VolumeOffIcon,
  'eye': EyeIcon,
  'eye-off': EyeOffIcon,
  'bar-chart': BarChartIcon,
  'trend-up': TrendUpIcon,
  'lightbulb': LightbulbIcon,
  'ban': BanIcon,
  'loader': LoaderIcon,
  'keyboard': KeyboardIcon,
};
